apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: iot-platform
  labels:
    app: mosquitto
    tier: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
        tier: messaging
    spec:
      containers:
        - name: mosquitto
          #image: eclipse-mosquitto:2.0.18
          image: eclipse-mosquitto:99.99.99-nonexistent
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 9001
              name: websocket
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: iot-platform
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    listener 9001
    protocol websockets
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: iot-platform
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: websocket
      port: 9001
      targetPort: 9001

